
version: '3'
services:

  jupyter:
    container_name: jupyter
    build:      .
    image:      jaeo/lifranum-notebook
    command:    pyspark --driver-memory 8g
    environment:
      PYSPARK_DRIVER_PYTHON: jupyter
      PYSPARK_DRIVER_PYTHON_OPTS: "notebook --NotebookApp.token='' --NotebookApp.notebook_dir='/content' "
      SPARK_PUBLIC_DNS: localhost
      JUPYTER_PORT: 8888
    ports:
      # Spark webUI. Starts at 4040 and increases each time a SparkContext is created
      - 4040-4042:4040-4042   
      - 8888:8888
    volumes:
      - ./content:/content
